### ISSUE TITLE
Stickers & keychains & Stattrack 

### ISSUE THREAD

**Issue by jxn78** [rogeraabbccdd/CS2-WeaponPaints-Web#1]
Does this version include stickers, stattrack, keychains?

**Comment by jxn78** [comment]
@rogeraabbccdd

**Comment by rogeraabbccdd** [comment]
Yes. they are all supported but with limitations.
- Stickers only support 4 default positions
- Keychain only support default position.
- Only support skins for all teams, setting skins for different teams is not supported.

**Comment by jxn78** [comment]
ok thanks for the answer 😁

**Comment by rogeraabbccdd** [comment]
66a20a24d57953aa6d631f589244582c51f2eb39 - Support 5 stickers
c66fbae79a50a1a6b5cbc264c736204b8d449c7b - Support sticker position, rotate, scale
aeaa288d781fb48b5fb0dd28c531fb3675d3d532 - Support keychain position
